### ISSUE TITLE
【①】NDA_努力義務

### ISSUE THREAD

**Issue by wada1239** [meti-oi-startups/METI-JPO-Model-Contract_AI#5]
## 議論をしたい契約書のタイトル

秘密保持

## 議論をしたい箇所

努力義務

## 該当箇所についてのコメント

＠＠＠

## 該当箇所の改定案

＠＠＠

**Comment by matsudaira22** [comment]
@wada1239 test 松平

**Comment by uedatakayuki** [comment]
テストなのでクローズします
