### ISSUE TITLE
【グループ2】第三者の権利侵害非保証をAI編にも記載してはどうか

### ISSUE THREAD

**Issue by meti-oi-startups-team** [meti-oi-startups/METI-JPO-Model-Contract_AI#8]
## 議論をしたい契約書のタイトル

利用契約書（AI編）

## 議論をしたい箇所

新素材編に記載のある第三者権利侵害非保証の記述をAI編にも記載して欲しい

**Comment by uedatakayuki** [comment]
@meti-oi-startups-team 
こちらAI編利用契約書の12条にも以下の非保証規定がありますが、どのような意図だったか覚えていらっしゃいますでしょうか。。？
<img width="555" alt="Screen Shot 2021-12-09 at 14 53 33" src="https://user-images.githubusercontent.com/34021140/145488545-36382982-deaa-418b-8903-1880fe519de3.png">

**Comment by meti-oi-startups-team** [comment]
@uedatakayuki 
ありがとうございます。ワークショップ参加者の方が仰っていたのですが､対応不要のようですのでCloseします｡
確認不足すみません｡

**Comment by uedatakayuki** [comment]
ご確認いただきましてありがとうございます！
